services:
  lcomhs:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./:/app
      - m2-cache:/root/.m2
    ports:
      - "8080:8080"
    environment:
      TAIGA_BASE_URL: https://swent0linux.asu.edu/taiga/api/v1
      TAIGA_USERNAME: 
      TAIGA_PASSWORD: 
      TAIGA_PROJECT_SLUG: group-4
      TAIGA_SPRINT_INDEX: "1"
      TAIGA_INSECURE_SSL: "true"
    command: >
      mvn -q clean compile exec:java
      -Dexec.mainClass=com.cohesion.Main
      -Dexec.args=src/main/java

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - lcomhs

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
  m2-cache: